
let frpgQLs = [

    {questline:"A Towering Investment",
    quest:"A Towering Investment I",
    info:`Cecil is looking for an investor to help with an archaeological excavation he is working on. He discovered an ancient tower buried deep underground several kilometers north of town. If his research is correct, this tower is filled with priceless treasure. If you will help him fund this project, he will give you a fair share of the treasure. Will you invest in Cecil’s excavation project? `,
    skills:[{skill:"Farming",value:90},{skill:"Fishing",value:90},{skill:"Crafting",value:90},{skill:"Exploring",value:90},],
    previous:undefined,
    next:"A Towering Investment II",
    requests:[{label:"Silver",quantity:2147483647,inventory:0},
    ],
    rewards:[{label:"Official Share",quantity:1,},],
    current:false,},

    {questline:"A Towering Investment",
    quest:"A Towering Investment II",
    info:`To help speed the excavation project, Cecil would like you to help provide food for the workers. The value of all the food you provide will go toward increasing your share of the treasure. Will you help provide food for the workers? `,
    skills:[{skill:"Farming",value:90},{skill:"Fishing",value:90},{skill:"Crafting",value:90},{skill:"Exploring",value:90},],
    previous:"A Towering Investment I",
    next:"A Towering Investment III",
    requests:[{label:"Apple",quantity:600,inventory:0},
    {label:"Broccoli",quantity:600,inventory:0},
    {label:"Cabbage",quantity:600,inventory:0},
    {label:"Eggs",quantity:600,inventory:0},
    {label:"Flour",quantity:600,inventory:0},
    {label:"Herbs",quantity:600,inventory:0},
    {label:"Leek",quantity:600,inventory:0},
    {label:"Milk",quantity:600,inventory:0},
    {label:"Mushroom",quantity:600,inventory:0},
    {label:"Onion",quantity:600,inventory:0},
    {label:"Peas",quantity:600,inventory:0},
    {label:"Peppers",quantity:600,inventory:0},
    {label:"Potato",quantity:600,inventory:0},
    {label:"Radish",quantity:600,inventory:0},
    {label:"Steak",quantity:600,inventory:0},
    ],
    rewards:[{label:"Official Share",quantity:1,},],
    current:false,},

    {questline:"A Towering Investment",
    quest:"A Towering Investment III",
    info:`Cecil would like you to provide additional nutritional variety for the workers. As before, this will add to your share of the treasure. `,
    skills:[{skill:"Farming",value:90},{skill:"Fishing",value:90},{skill:"Crafting",value:90},{skill:"Exploring",value:90},],
    previous:"A Towering Investment II",
    next:"A Towering Investment IV",
    requests:[{label:"Lemon",quantity:600,inventory:0},
    {label:"Orange",quantity:600,inventory:0},
    {label:"Cucumber",quantity:600,inventory:0},
    {label:"Carrot",quantity:600,inventory:0},
    {label:"Corn",quantity:600,inventory:0},
    {label:"Catfish",quantity:600,inventory:0},
    {label:"Honey",quantity:600,inventory:0},
    {label:"Eggplant",quantity:600,inventory:0},
    {label:"Mackerel",quantity:600,inventory:0},
    {label:"Pumpkin",quantity:600,inventory:0},
    {label:"Salt",quantity:600,inventory:0},
    {label:"Shrimp",quantity:600,inventory:0},
    {label:"Small Prawn",quantity:600,inventory:0},
    {label:"Watermelon",quantity:600,inventory:0},
    {label:"Tomato",quantity:600,inventory:0},
    ],
    rewards:[{label:"Official Share",quantity:1,},],
    current:false,},

    {questline:"A Towering Investment",
    quest:"A Towering Investment IV",
    info:`Cecil thinks the food supply needs a few more things. `,
    skills:[{skill:"Farming",value:90},{skill:"Fishing",value:90},{skill:"Crafting",value:90},{skill:"Exploring",value:90},],
    previous:"A Towering Investment III",
    next:"A Towering Investment V",
    requests:[{label:"Mussel",quantity:600,inventory:0},
    {label:"Beet",quantity:600,inventory:0},
    {label:"Bacon",quantity:600,inventory:0},
    {label:"Crab Claw",quantity:100,inventory:0},
    {label:"Seaweed",quantity:600,inventory:0},
    {label:"Sea Catfish",quantity:600,inventory:0},
    {label:"Giant Squid",quantity:600,inventory:0},
    {label:"Puffer",quantity:600,inventory:0},
    {label:"Flarefin",quantity:600,inventory:0},
    {label:"Sweet Root",quantity:600,inventory:0},
    {label:"Sour Root",quantity:600,inventory:0},
    {label:"Swordfish",quantity:600,inventory:0},
    {label:"Red Berries",quantity:600,inventory:0},
    {label:"Cheese",quantity:600,inventory:0},
    {label:"Wine",quantity:200,inventory:0},
    ],
    rewards:[{label:"Official Share",quantity:1,},],
    current:false,},

    {questline:"A Towering Investment",
    quest:"A Towering Investment V",
    info:`Several workers were injured while excavating a section of the tower yesterday. Cecil would like you to increase your monetary investment to provide care for those injured, and to help hire additional workers. Will you invest more silver in Cecil’s project? `,
    skills:[{skill:"Farming",value:90},{skill:"Fishing",value:90},{skill:"Crafting",value:90},{skill:"Exploring",value:90},],
    previous:"A Towering Investment IV",
    next:"A Towering Investment VI",
    requests:[{label:"Silver",quantity:2147483647,inventory:0},
    ],
    rewards:[{label:"Official Share",quantity:1,},],
    current:false,},

    {questline:"A Towering Investment",
    quest:"A Towering Investment VI",
    info:`To help reduce costs, Cecil would like you to supply tools and materials for the workers to continue the excavation process. The value will be added as before to your share of the treasure. Will you provide tools and materials? `,
    skills:[{skill:"Farming",value:90},{skill:"Fishing",value:90},{skill:"Crafting",value:90},{skill:"Exploring",value:90},],
    previous:"A Towering Investment V",
    next:"A Towering Investment VII",
    requests:[{label:"Board",quantity:600,inventory:0},
    {label:"Bucket",quantity:600,inventory:0},
    {label:"Hammer",quantity:600,inventory:0},
    {label:"Iron",quantity:600,inventory:0},
    {label:"Lantern",quantity:600,inventory:0},
    {label:"Nails",quantity:600,inventory:0},
    {label:"Shovel",quantity:600,inventory:0},
    {label:"Axe",quantity:600,inventory:0},
    {label:"Steel",quantity:600,inventory:0},
    {label:"Rope",quantity:600,inventory:0},
    {label:"Wagon Wheel",quantity:600,inventory:0},
    {label:"Wooden Plank",quantity:600,inventory:0},
    {label:"Wooden Barrel",quantity:600,inventory:0},
    {label:"Pine Tree",quantity:600,inventory:0},
    ],
    rewards:[{label:"Official Share",quantity:1,},],
    current:false,},

    {questline:"A Towering Investment",
    quest:"A Towering Investment VII",
    info:`The tower is larger than Cecil’s initial analysis showed. The excavation is going to cost significantly more than Cecil planned. Will you increase your investment again? `,
    skills:[{skill:"Farming",value:90},{skill:"Fishing",value:90},{skill:"Crafting",value:90},{skill:"Exploring",value:90},],
    previous:"A Towering Investment VI",
    next:"A Towering Investment VIII",
    requests:[{label:"Silver",quantity:2147483647,inventory:0},
    ],
    rewards:[{label:"Official Share",quantity:1,},],
    current:false,},

    {questline:"A Towering Investment",
    quest:"A Towering Investment VIII",
    info:`The excavation project needs more tools and materials. Will you provide more supplies? `,
    skills:[{skill:"Farming",value:90},{skill:"Fishing",value:90},{skill:"Crafting",value:90},{skill:"Exploring",value:90},],
    previous:"A Towering Investment VII",
    next:"A Towering Investment IX",
    requests:[{label:"Oak",quantity:600,inventory:0},
    {label:"Wood",quantity:600,inventory:0},
    {label:"Wooden Plank",quantity:600,inventory:0},
    {label:"Straw",quantity:600,inventory:0},
    {label:"Sand",quantity:600,inventory:0},
    {label:"Stone",quantity:600,inventory:0},
    {label:"Steel",quantity:600,inventory:0},
    {label:"Board",quantity:600,inventory:0},
    {label:"Broom",quantity:600,inventory:0},
    {label:"Emberstone",quantity:600,inventory:0},
    {label:"Hammer",quantity:600,inventory:0},
    {label:"Shovel",quantity:600,inventory:0},
    {label:"Ladder",quantity:600,inventory:0},
    {label:"Coal",quantity:600,inventory:0},
    ],
    rewards:[{label:"Official Share",quantity:1,},],
    current:false,},

    {questline:"A Towering Investment",
    quest:"A Towering Investment IX",
    info:`Cecil noticed that the workers need more food supplies. Will you continue to supply food for the workers? `,
    skills:[{skill:"Farming",value:92},{skill:"Fishing",value:92},{skill:"Crafting",value:92},{skill:"Exploring",value:92},],
    previous:"A Towering Investment VIII",
    next:"A Towering Investment X",
    requests:[{label:"Apple",quantity:700,inventory:0},
    {label:"Bacon",quantity:700,inventory:0},
    {label:"Lemon",quantity:700,inventory:0},
    {label:"Orange",quantity:700,inventory:0},
    {label:"Beet",quantity:700,inventory:0},
    {label:"Cabbage",quantity:700,inventory:0},
    {label:"Broccoli",quantity:700,inventory:0},
    {label:"Carrot",quantity:700,inventory:0},
    {label:"Corn",quantity:700,inventory:0},
    {label:"Eggs",quantity:700,inventory:0},
    {label:"Flour",quantity:700,inventory:0},
    {label:"Leek",quantity:700,inventory:0},
    {label:"Grapes",quantity:700,inventory:0},
    {label:"Flamejack",quantity:700,inventory:0},
    {label:"Largemouth Bass",quantity:700,inventory:0},
    {label:"Ruby Fish",quantity:700,inventory:0},
    {label:"Iced Tea",quantity:700,inventory:0},
    ],
    rewards:[{label:"Official Share",quantity:1,},],
    current:false,},

    {questline:"A Towering Investment",
    quest:"A Towering Investment X",
    info:`Cecil wants to add a little something extra to the workers’ diet. He thinks the magical properties of golden fish could really boost the speed of the excavation project. Will you bring a supply of different golden fish? `,
    skills:[{skill:"Farming",value:92},{skill:"Fishing",value:92},{skill:"Crafting",value:92},{skill:"Exploring",value:92},],
    previous:"A Towering Investment IX",
    next:"A Towering Investment XI",
    requests:[{label:"Gold Catfish",quantity:150,inventory:0},
    {label:"Gold Drum",quantity:150,inventory:0},
    {label:"Gold Flier",quantity:150,inventory:0},
    {label:"Gold Sea Bass",quantity:150,inventory:0},
    {label:"Gold Trout",quantity:150,inventory:0},
    {label:"Goldfin",quantity:150,inventory:0},
    {label:"Goldgill",quantity:150,inventory:0},
    {label:"Goldjack",quantity:150,inventory:0},
    {label:"Goldray",quantity:150,inventory:0},
    ],
    rewards:[{label:"Official Share",quantity:1,},],
    current:false,},

    {questline:"A Towering Investment",
    quest:"A Towering Investment XI",
    info:`The excavation team has reached the tower’s foundation! The excavation work is finished! Unfortunately, there’s no way to open the doors to the tower. However, Cecil has an idea that should get the doors open. On each level of the tower, the workers discovered an intricate and linked series of mechanisms. Cecil thinks that this machinery can be cleaned and repaired and set to working order. The unfortunate part of this plan is that it will require one more investment of silver to fund the repair work. Will you invest in repairing the tower’s external mechanisms? `,
    skills:[{skill:"Farming",value:92},{skill:"Fishing",value:92},{skill:"Crafting",value:92},{skill:"Exploring",value:92},],
    previous:"A Towering Investment X",
    next:"A Towering Investment XII",
    requests:[{label:"Silver",quantity:2147483647,inventory:0},
    ],
    rewards:[{label:"Official Share",quantity:1,},],
    current:false,},

    {questline:"A Towering Investment",
    quest:"A Towering Investment XII",
    info:`Cecil would like your help with another cost-saving measure for the tower project. If you will help supply parts for repairing the tower machinery, it will be a huge reduction in expenditure and time lost. As usual, your contributions will go toward your shares in the treasure. `,
    skills:[{skill:"Farming",value:92},{skill:"Fishing",value:92},{skill:"Crafting",value:92},{skill:"Exploring",value:92},],
    previous:"A Towering Investment XI",
    next:"A Towering Investment XIII",
    requests:[{label:"Small Screw",quantity:700,inventory:0},
    {label:"Small Spring",quantity:700,inventory:0},
    {label:"Cogwheel",quantity:700,inventory:0},
    {label:"Steel Wire",quantity:700,inventory:0},
    {label:"Steel",quantity:700,inventory:0},
    {label:"Magna Quartz",quantity:100,inventory:0},
    {label:"Small Gear",quantity:100,inventory:0},
    {label:"Flywheel",quantity:100,inventory:0},
    ],
    rewards:[{label:"Official Share",quantity:1,},],
    current:false,},

    {questline:"A Towering Investment",
    quest:"A Towering Investment XIII",
    info:`The repairs are a little more difficult than expected. Will you invest more silver to help find and fund experts in machine repairs? `,
    skills:[{skill:"Farming",value:92},{skill:"Fishing",value:92},{skill:"Crafting",value:92},{skill:"Exploring",value:92},],
    previous:"A Towering Investment XII",
    next:"A Towering Investment XIV",
    requests:[{label:"Silver",quantity:2147483647,inventory:0},
    ],
    rewards:[{label:"Official Share",quantity:1,},],
    current:false,},

    {questline:"A Towering Investment",
    quest:"A Towering Investment XIV",
    info:`Some of the tower mechanisms require different stones and gems to function. Will you help Cecil gather the required resources? `,
    skills:[{skill:"Farming",value:92},{skill:"Fishing",value:92},{skill:"Crafting",value:92},{skill:"Exploring",value:92},],
    previous:"A Towering Investment XIII",
    next:"A Towering Investment XV",
    requests:[{label:"Runestone 01",quantity:4,inventory:0},
    {label:"Runestone 02",quantity:4,inventory:0},
    {label:"Runestone 03",quantity:4,inventory:0},
    {label:"Runestone 04",quantity:4,inventory:0},
    {label:"Runestone 05",quantity:4,inventory:0},
    {label:"Runestone 06",quantity:4,inventory:0},
    {label:"Runestone 07",quantity:4,inventory:0},
    {label:"Runestone 08",quantity:4,inventory:0},
    {label:"Runestone 09",quantity:4,inventory:0},
    {label:"Runestone 10",quantity:4,inventory:0},
    {label:"Amethyst",quantity:700,inventory:0},
    {label:"Aquamarine",quantity:700,inventory:0},
    {label:"Carbon Sphere",quantity:700,inventory:0},
    {label:"Emerald",quantity:700,inventory:0},
    {label:"Ruby",quantity:700,inventory:0},
    ],
    rewards:[{label:"Official Share",quantity:1,},],
    current:false,},

    {questline:"A Towering Investment",
    quest:"A Towering Investment XV",
    info:`Cecil found that more stones and gems are needed for the tower mechanisms. Will you bring the stones and gems needed? `,
    skills:[{skill:"Farming",value:92},{skill:"Fishing",value:92},{skill:"Crafting",value:92},{skill:"Exploring",value:92},],
    previous:"A Towering Investment XIV",
    next:"A Towering Investment XVI",
    requests:[{label:"Runestone 11",quantity:4,inventory:0},
    {label:"Runestone 12",quantity:4,inventory:0},
    {label:"Runestone 13",quantity:4,inventory:0},
    {label:"Runestone 14",quantity:4,inventory:0},
    {label:"Runestone 15",quantity:4,inventory:0},
    {label:"Runestone 16",quantity:4,inventory:0},
    {label:"Runestone 17",quantity:4,inventory:0},
    {label:"Runestone 18",quantity:4,inventory:0},
    {label:"Runestone 19",quantity:4,inventory:0},
    {label:"Runestone 20",quantity:4,inventory:0},
    {label:"Garnet",quantity:700,inventory:0},
    {label:"Jade",quantity:700,inventory:0},
    {label:"Lemon Quartz",quantity:700,inventory:0},
    {label:"Moonstone",quantity:700,inventory:0},
    {label:"Pearl",quantity:700,inventory:0},
    {label:"Magicite",quantity:700,inventory:0},
    {label:"Shimmer Topaz",quantity:700,inventory:0},
    ],
    rewards:[{label:"Official Share",quantity:1,},],
    current:false,},

    {questline:"A Towering Investment",
    quest:"A Towering Investment XVI",
    info:`Cecil thinks the tower machinery is ready to be activated. Before attempting to activate the tower, Cecil would like to have an assortment of items available in case the mechanisms need some additional magical energy. Will you provide the needed items for an additional share in the tower treasure? `,
    skills:[{skill:"Farming",value:92},{skill:"Fishing",value:92},{skill:"Crafting",value:92},{skill:"Exploring",value:92},],
    previous:"A Towering Investment XV",
    next:"A Towering Investment XVII",
    requests:[{label:"Arrowhead",quantity:700,inventory:0},
    {label:"Blue Gel",quantity:700,inventory:0},
    {label:"Bone Fish",quantity:700,inventory:0},
    {label:"Dragonfly",quantity:400,inventory:0},
    {label:"Frog",quantity:100,inventory:0},
    {label:"Orange Gecko",quantity:100,inventory:0},
    {label:"Gold Leaf",quantity:300,inventory:0},
    {label:"Gold Feather",quantity:300,inventory:0},
    {label:"Gold Coral",quantity:150,inventory:0},
    {label:"Gold Peppers",quantity:500,inventory:0},
    {label:"Grasshopper",quantity:400,inventory:0},
    {label:"Purple Flower",quantity:700,inventory:0},
    {label:"Thorns",quantity:700,inventory:0},
    {label:"Water Lily",quantity:300,inventory:0},
    {label:"Spiked Shell",quantity:100,inventory:0},
    {label:"Cotton",quantity:700,inventory:0},
    {label:"Globber",quantity:700,inventory:0},
    {label:"Ruby Scorpion",quantity:700,inventory:0},
    {label:"Sea Dragon",quantity:100,inventory:0},
    ],
    rewards:[{label:"Official Share",quantity:1,},],
    current:false,},

    {questline:"A Towering Investment",
    quest:"A Towering Investment XVII",
    info:`The doors to the tower are open! Cecil has enlisted ROOMBA to do an initial exploration and cleaning of the tower. Will you bring corn to help power ROOMBA’s work? `,
    skills:[{skill:"Farming",value:92},{skill:"Fishing",value:92},{skill:"Crafting",value:92},{skill:"Exploring",value:92},],
    previous:"A Towering Investment XVI",
    next:"A Towering Investment XVIII",
    requests:[{label:"Corn",quantity:700,inventory:0},
    ],
    rewards:[{label:"Official Share",quantity:1,},],
    current:false,},

    {questline:"A Towering Investment",
    quest:"A Towering Investment XVIII",
    info:`ROOMBA’s inspection of the tower is complete! The tower looks to be functional and safe, and surprisingly well preserved on the inside. Cecil also went ahead and performed his own inspection of the tower, and gathered his share of the treasure. He hopes you do not mind him proceeding without you. Cecil thinks the tower is now ready for your use. In fact, as thanks for your enormous and incredible investment, Cecil would like to turn over the stewardship of the tower to you. He will retain a small role in the management of the tower, but he will leave its normal use, exploration, and operations to you. `,
    skills:[{skill:"Farming",value:92},{skill:"Fishing",value:92},{skill:"Crafting",value:92},{skill:"Exploring",value:92},],
    previous:"A Towering Investment XVII",
    next:undefined,
    requests:[{label:"Official Share",quantity:17,inventory:0},
    ],
    rewards:[{label:"Tower Key",quantity:1,},],
    current:false,},

    ////////////////////////////////////////////////////////////////////////

    {questline:"A Wall In The Way",
    quest:"A Wall In The Way I",
    info:`Dark clouds on the horizon, you check your mailbox and find a letter. I hope this letter finds you well. It burdens my heart to write you this, but I think our dear friend Thomas is not well. He has seemed distant of late, and complained of various ailments that my books cannot identify. Would you be so kind as to join me for dinner tomorrow night with our esteemed friend? Since you’ll be in the area, could you help me restock my stores as well? A list of ingredients and fish follow. `,
    skills:[{skill:"Farming",value:91},{skill:"Fishing",value:90},],
    previous:"Intruders Beware XI",
    next:"A Wall In The Way II",
    requests:[{label:"Cabbage",quantity:500,inventory:0},
    {label:"Corn",quantity:500,inventory:0},
    {label:"Rice",quantity:500,inventory:0},
    {label:"Steak",quantity:500,inventory:0},
    {label:"Orcafish",quantity:500,inventory:0},
    {label:"Gold Drum",quantity:150,inventory:0},
    {label:"Lima Bean",quantity:5,inventory:0},
    {label:"Sunflower",quantity:2,inventory:0},
    {label:"Sea Dragon",quantity:100,inventory:0},
    {label:"Spiked Shell",quantity:100,inventory:0},
    {label:"Honey",quantity:300,inventory:0},
    ],
    rewards:[{label:"Silver",quantity:700000000,},
    {label:"Large Chest 02",quantity:50,},
    ],
    current:false,},

    {questline:"A Wall In The Way",
    quest:"A Wall In The Way II",
    info:`The evening approaches and you head to Lorn’s home. The sky is peaceful, almost serene after looking dark previously. Your steps feel light and you take a deep breath of the evening air. Lorn is on his porch, chatting amiably with Thomas when you arrive. You catch the tail end of their conversation. “…estimated! I just have to prove to you I can be better.” Lorn chuckles as you walk up his porch steps, “Hello there! Won’t you join us for dinner? The supplies can all be stocked later tonight.” As Lorn stands, he seems older, more frail than you remember. Maybe it’s a trick of the evening light, you think to yourself. At dinnertime, you all enjoy a well prepared meal out of some of the ingredients you brought, and some strange fish you don’t recognize. Thomas and Lorn again begin to talk spiritedly. Lorn’s eyes positively gleam the entire time, returning the youthful countenance you view in him, despite his advancing age. “You just gotta let me prove to you that I’ve gotten better! Our friend here has seen it firsthand! Look at the haul we’ve made at Pirate’s Cove! I was a part of that, you know…” Before Thomas continues, you notice a slight hitch in Thomas’s arm as he winces, spearing a piece of fish. “What is this fish anyways?” “It’s extremely rare. In fact, no one I know could find or identify it, but the trader called it a Glassback, it’s not native to our oceans or lakes, so I’ve no idea how they came across it, but I paid a pretty penny for the privilege. I bought it a few months ago but never had the right time to share it, but now seems as good as any, eh?” You mention how good the fish is, and Thomas agrees. Lorn suggests you reconvene on the deck. “Would you like to hear about a lake encircled in ice?” `,
    skills:[{skill:"Fishing",value:90},],
    previous:"A Wall In The Way I",
    next:"A Wall In The Way III",
    requests:[{label:"MIAB",quantity:200,inventory:0},
    {label:"Purple Butterfly Fish",quantity:600,inventory:0},
    {label:"Jumbo Fish",quantity:600,inventory:0},
    {label:"Model Ship",quantity:1,inventory:0},
    ],
    rewards:[{label:"Silver",quantity:200000000,},
    {label:"Gold Eggplant Seeds",quantity:500,},
    ],
    current:false,},

    {questline:"A Wall In The Way",
    quest:"A Wall In The Way III",
    info:`Thomas can hardly contain himself as you sit on the porch, he squirms uncomfortably and impatiently, between odd winces. Lorn looks at the sunset and smiles, seeming unhurried by the circumstances he has created. You take a sip of tea, knowing that good things come to those who wait. “Before Thomas wears a hole in my porch, let me tell you what I know…” Thomas stares at Lorn with rapt attention. “In the days before, legend tells us the guardians of the world were sent forth to oversee the land, to give it a final shape and form. To walk amongst the people and care for them as one might care for a flock. Among them was Zho, though you might know them as Zholice or perhaps Shva, their ancient name is written in books I have read. Zho was the guardian of water and sapphire and they made their home among the people. There are legends of an unending cold known as Shva’s Playground, and within it lies Zho’s Lake. The lake is as clear as day, and it’s said you can walk on the lake and ice will form under your feet as you walk.” Lorn guffaws, “Fairy tales, I tell you…” After another pause, he continues “Other legends say that there is but one stream that leaves the lake, and that is how a fish from that mythical place could be found in the ocean. These fish are so rare, their value would be greater than anything you’ve seen so far. I didn’t believe it myself until I discovered the one from tonight a few months back.” Thomas, leaning over the balcony, looks back to you both. “I’m gonna find that Lake, and I’m gonna fish up the best fish you’ve ever had Lorn, on my honor!” He looks to you and says, “Pack your things, we’re going north!” As he strides away, Lorn carries a wistful but knowing smile as he turns back to his house. “But I haven’t finished my story…” You wonder if Lorn hadn’t planned this all along, but in the meantime, you realize you need to prepare for a trek to the north. `,
    skills:[{skill:"Fishing",value:90},],
    previous:"A Wall In The Way II",
    next:"A Wall In The Way IV",
    requests:[{label:"Green Scarf",quantity:600,inventory:0},
    {label:"Cutlass",quantity:10,inventory:0},
    {label:"Green Cloak",quantity:250,inventory:0},
    {label:"Sturdy Shield",quantity:600,inventory:0},
    {label:"Sturdy Bow",quantity:600,inventory:0},
    {label:"Sturdy Sword",quantity:600,inventory:0},
    ],
    rewards:[{label:"Arnold Palmer",quantity:50,},
    {label:"Cotton Seeds",quantity:200,},
    {label:"Mushroom Paste",quantity:600,},
    {label:"Ancient Coin",quantity:100,},
    {label:"Gold Cucumber Seeds",quantity:500,},
    ],
    current:false,},

    {questline:"A Wall In The Way",
    quest:"A Wall In The Way IV",
    info:`You wake up the next morning to a loud banging at your door. Groggily, you find Thomas, looking full of energy and excitement standing in front of you. “We can’t leave today, I know, you need to make plans, so I have an idea too. Maybe we should use some parts from the rest of your journeys to make our current journey easier. I’ve asked Jill for a little help in the designs…” `,
    skills:[{skill:"Fishing",value:90},],
    previous:"A Wall In The Way III",
    next:"A Wall In The Way V",
    requests:[{label:"Energy Coil",quantity:100,inventory:0},
    {label:"Pear Grease",quantity:100,inventory:0},
    {label:"Spool of Copper",quantity:100,inventory:0},
    {label:"Metal Spool",quantity:500,inventory:0},
    {label:"Belt Drive",quantity:500,inventory:0},
    {label:"Corn Oil",quantity:100,inventory:0},
    ],
    rewards:[{label:"Onion Soup",quantity:5,},
    {label:"Neigh",quantity:5,},
    {label:"Shrimp-a-Plenty",quantity:5,},
    {label:"Grab Bag 08",quantity:100,},
    {label:"Langstaff Crest",quantity:1,},
    ],
    current:false,},

    {questline:"A Wall In The Way",
    quest:"A Wall In The Way V",
    info:`After delivering the requested items to Jill, you gather a few more things before setting forth. Of extreme importance is food, clothing, and general traveling supplies. The day of the trip you agreed on with Thomas comes and Thomas is nowhere to be found. You find him later in his cabin, collapsed on the floor. Lorn looks to you, “He seems to have taken a nasty spill. I noticed him acting oddly lately, but didn’t expect anything like this. I suggested the trip because I suspected a goal might help with whatever ails him, but it doesn’t seem to have made much difference.” After a moment of consideration, you suggest that it has in fact invigorated him, as you noticed in his interactions less of the odd behavior. Between the two of you, you decide not to talk to Thomas more about this incident and proceed as planned after Thomas awakens. `,
    skills:[{skill:"Fishing",value:90},],
    previous:"A Wall In The Way IV",
    next:"A Wall In The Way VI",
    requests:[{label:"Green Cloak",quantity:600,inventory:0},
    {label:"Fern Leaf",quantity:600,inventory:0},
    {label:"Yarn",quantity:600,inventory:0},
    {label:"Green Scarf",quantity:600,inventory:0},
    ],
    rewards:[{label:"Silver",quantity:250000000,},
    {label:"Arnold Palmer",quantity:50,},
    ],
    current:false,},

    {questline:"A Wall In The Way",
    quest:"A Wall In The Way VI",
    info:`The trek north is slow but steady progress. The carts carrying your snow machines are well prepared thanks to the weight balancing steel plates and large tyres with treads Jill added. They also work off a strange system of wheel propulsion you nor Thomas understand, but they lighten your trek significantly and make obstructions significantly easier to navigate. A week of traveling, past Cane Pole Ridge and farther north, you’re surprised to find rolling hills that never seem to break into a flatland or a mountain range. On the break of the ninth day, you see in the distance a bright gleam of sun, dazzling your eyes, you realize this might be the direction you seek. You change tack to the northwest and the temperature begins to drop precipitously. Ice begins to take over the landscape, and yet to the east and west, you see nothing but clear skies and green fields. “This feels right,” Thomas says excitedly, “We’re gonna find this place and I’m gonna be the greatest fisherman slash explorer in Redbrook!” You both make camp for the night and prepare for a journey into frozen lands in the morning. Thomas seems somehow brighter through this experience, and you haven’t noticed any of the odd ticks from the previous days. Maybe Lorn was right, you think to yourself. You both spend the better part of the morning trying to figure out exactly how Jill got these contraptions *on* the cart to begin with. While looking over the machines more thoroughly, you spy a big red button labeled “Start”. Exhausted, you hop on and when you press the start button, the snow machine comes whirring to life. Gears begin turning and before you know it the treads on the backs of the machine start spinning slowly and you begin inching forward. Thomas laughs triumphantly and yells, “It’s working! It’s working! Well, at least I think that’s what Jill might say.” After a moment of revelry, you press the button again and the machine abruptly stops. You notice at that point a letter from Jill taped to the side of the machine with specific unloading instructions as well as operating instructions. “Friends, Here are my new creations, schematics I had only dreamed of until I heard of the parts you’d found in the Jundland Wastes – please take care of them, I’d be ever so sad never to see them again. Your friend, Jill (not a farmer)”`,
    skills:[],
    previous:"A Wall In The Way V",
    next:"A Wall In The Way VII",
    requests:[{label:"Corn Oil",quantity:100,inventory:0},
    ],
    rewards:[{label:"Silver",quantity:200000000,},
    {label:"Steel",quantity:600,},
    {label:"Wagon Wheel",quantity:4,},
    {label:"Machine Press",quantity:20,},
    ],
    current:false,},

    {questline:"A Wall In The Way",
    quest:"A Wall In The Way VII",
    info:`After half an hour, you both feel comfortable enough with the machinery to start traveling with it, so you set off. The machines are not very noisy, but the occasional clang and ping is quite jarring in the quiet intensity of the growing cold and snow as you travel further north. For each minute that passes, you grow more and more unsettled. Distinctly to the east and west you can still see green. The area slowly grows more forested in all directions but only in the small swathe of land you travel is there snow as it slopes gently upwards. Slowly over the next hour the snow-covered land expands on both sides, greenery becoming overtaken by white, making you believe you started near the point of this mysterious phenomenon. Thomas seems determined to trek onward, and his determination is met suddenly by a fierce blowing wind. Snow begins falling from the sky at a rapid pace, though no clouds appear overhead. The effect of wind, snow, and bright sun are disorienting, the light glinting off the snow crystals creating beautiful fleeting patterns of reflected light all around you. You both lean forward, almost willing your machines to traverse the snow faster as the winds intensify until suddenly, you reach a barrier of snow, ice, and wind. “It’s too dangerous!” you shout to Thomas. The roaring maelstrom in front of you fills you with terror and a hint of sorrow. “We must go back!” Thomas looks to you, a mad gleam in his eye, “No!” You try to call out again, but Thomas lurches forward. His machine begins to enter the maelstrom and as he enters you hear an unearthly roar from all around you as Thomas and the snow contraption are both lifted into the air. Ice covers the machine and Thomas is thrown viciously backwards. He crumples to the ground unnaturally and the storm subsides as you run towards Thomas. `,
    skills:[{skill:"Fishing",value:90},],
    previous:"A Wall In The Way VI",
    next:"A Wall In The Way VIII",
    requests:[{label:"Strange Ring",quantity:5,inventory:0},
    ],
    rewards:[{label:"Silver",quantity:500000000,},
    ],
    current:false,},

    {questline:"A Wall In The Way",
    quest:"A Wall In The Way VIII",
    info:`Thomas is cold and lifeless as you approach him. He seems to have faded in some ways. Frost creeps up his fingers unnaturally. It seems slow, almost imperceptible, but after a quick check he is breathing. You pick up Thomas as gingerly as possible, the cold seems to emanate from his body, penetrating all the layers of covering you’re wearing. Gingerly, you put Thomas in front of you on the snow machine and rush back the way you came. Lorn will know what to do, the thought crosses your mind. You return to the edge of the phenomenon and quickly fashion a makeshift cart for Thomas. Jill's going to be very mad at me as well, you think to yourself as you leave the snow machine behind. You grab the cart, make sure Thomas is safe, and rush back to Redbrook. The trip takes less time, as you skip breaks, traveling on minimal sleep, you travel recklessly to get back sooner. Each time you check on Thomas, you see the frost has crawled farther up his arms and legs. Exhausted, you reach Redbrook after seven days of hard, almost ceaseless travel and caring for Thomas the best you can, you find yourself collapsing on Lorn’s doorstep. Lorn opens his door as you weakly gesture towards the cart and even though you are pointing towards the cart, you don’t understand why Lorn is trying to help you to a chair. “You fools. You bloody fools!” The words come from Lorn's mouth, but you hear Star Meerif's voice. `,
    skills:[{skill:"Fishing",value:90},],
    previous:"A Wall In The Way VII",
    next:"A Wall In The Way IX",
    requests:[{label:"Piece of Heart",quantity:1,inventory:0},
    ],
    rewards:[{label:"Silver",quantity:100000000,},
    {label:"Grape Juice",quantity:100,},
    ],
    current:false,},

    {questline:"A Wall In The Way",
    quest:"A Wall In The Way IX",
    info:`You feel something tickle your nose and startle you back to consciousness, but your eyes won’t open despite your best efforts. “YOU SENT THEM TO SHVA’S PLAYGROUND!? In the name of Tvas, why would you do that, Lorn?” “Sometimes, people need a push. You, of all people should respect this given your long history. It was not my choice, but theirs. I just… gave them a little nudge out the door. It was for his own good.” “…It’s enchanted, and powerfully so. Every book and being I’ve ever spoken with, including text from the Golden Leaf tell us to stay away! Even I am not stupid enough to try and penetrate Shva’s Wall.” “Be that as it may, you’re obligated to help these two now, you’ve heard Thomas’ plight, it is beyond their abilities.” “I am obligated to do no such thing. You think I'm a fool? Yes, and before you say it, that business before was different. Shva is not to be trifled with and I…am not knowledgeable enough, not by half in some of those realms to do what you seek.” A pause. “Cecil, then?” A long, uncomfortable pause follows. “If you must continue this folly.” You feel another tickle on your nose. “He won’t get better if we avoid the problem, Star.” There is no response, and you lose consciousness again. `,
    skills:[{skill:"Fishing",value:90},],
    previous:"A Wall In The Way VIII",
    next:"A Wall In The Way X",
    requests:[{label:"Feathers",quantity:600,inventory:0},
    {label:"Gold Feather",quantity:250,inventory:0},
    {label:"Shimmer Ring",quantity:600,inventory:0},
    {label:"Dragon Skull",quantity:5,inventory:0},
    {label:"Honey",quantity:300,inventory:0},
    ],
    rewards:[{label:"Wizard Hat",quantity:1,},
    ],
    current:false,},

    {questline:"A Wall In The Way",
    quest:"A Wall In The Way X",
    info:`You awaken the next morning, and Lorn gives you some more medicine, with orders to take things slow and try not to overdo it over the next few days. You are quickly escorted out of the room and as you leave, you catch a glimpse of Thomas, pale but no longer covered in frost. “He needs rest, but you and Star saved his life, no thanks to me.” He says softly. A look of remorse passes his features quickly. After a week of taking things easy, returning to your normal routine has helped your recovery immensely. A balanced diet of orange juice, lemonade, tea, and occasionally lemonade and tea mixed have helped re-hydrate you, and a balanced meal has restored your strength. `,
    skills:[{skill:"Fishing",value:90},],
    previous:"A Wall In The Way IX",
    next:"A Wall In The Way XI",
    requests:[{label:"Orange Juice",quantity:250,inventory:0},
    {label:"Lemonade",quantity:250,inventory:0},
    {label:"Arnold Palmer",quantity:50,inventory:0},
    {label:"Steak",quantity:500,inventory:0},
    {label:"Steak Kabob",quantity:500,inventory:0},
    {label:"Iced Tea",quantity:500,inventory:0},
    {label:"Rice",quantity:500,inventory:0},
    {label:"Salt",quantity:500,inventory:0},
    ],
    rewards:[{label:"Silver",quantity:1000000000,},
    {label:"Gold Carrot Seeds",quantity:500,},
    {label:"Grab Bag 04",quantity:100,},
    {label:"Grab Bag 05",quantity:100,},
    {label:"Fruit Punch",quantity:20,},
    {label:"Antler",quantity:500,},
    ],
    current:false,},

    {questline:"A Wall In The Way",
    quest:"A Wall In The Way XI",
    info:`Each day during this week, you have checked on Thomas and his health has returned much more quickly than you or Lorn have anticipated. Lorn has spent much time researching the effects of the item Star requested for healing, but he seems to refuse to want to ask for more information, content to find old parchments in his basement and mutter to himself from beside Thomas’ bed. Thomas on the other hand has been pressing Lorn for as much information on Shva and Shva’s Wall. On one occasion, Lorn let slip that Star or Cecil might know more about it. After two weeks, despite both you and Lorn’s protests to the contrary, Thomas’ inquiries into Shva’s Wall have only grown more persistent and with begrudging consent from Lorn, and Thomas’ insistence that he would pursue this with or without you, you’ve found yourself joining Thomas on a trip to Cecil’s manor. Before the third knock, the door opens, and Cecil appears before you both. His clothes are different from what you remember, more like robes than his typical business attire and he seems quite irate. “What do you want? I’m very busy.” Thomas shuffles his feet, clearly not expecting this rough welcome. He mumbles through a greeting before clearly stating, “I want to get through Shva’s Wall.” Cecil was clearly not expecting this forward statement from Thomas and his face breaks out into a broad smile. “My dear fellow, why didn’t you say that sooner? Come in, come in.” You step inside Cecil's home. Somehow, the opulence of his home continues to amaze you, the large hall, filled with baubles, gems and other devices always takes your breath away. You recall the room you visited with the energy core, but Cecil instead takes you to his dining room, where three sets of cups, a tea kettle, milk, and sugar are in the middle of the table. Before you can ask how Cecil had these ready, he begins speaking as you sit down. “I heard rumors that hooligan Star wouldn’t help you out, so I’ve been doing a little research of my own and found I might already have something to help you with your journey, if you’re willing to pay the price.” Thomas looks intensely at Cecil, “I’ll pay any price.” Cecil looks to you both, “Great, let’s have some tea and discuss the…tea.” Cecil laughs to himself, but you don’t quite understand why. `,
    skills:[{skill:"Fishing",value:90},],
    previous:"A Wall In The Way X",
    next:"A Wall In The Way XII",
    requests:[{label:"Tea Leaves",quantity:500,inventory:0},
    {label:"Iced Tea",quantity:500,inventory:0},
    ],
    rewards:[{label:"Arnold Palmer",quantity:100,},
    ],
    current:false,},

    {questline:"A Wall In The Way",
    quest:"A Wall In The Way XII",
    info:`“Zho was the guardian of water in our world. Their Playground is where they experimented with their Power and where their followers gathered in tribute and followed Zho’s teachings. As the years went on, Zho shared what they learned of Power with others, and the Playground eventually grew into a temple. Zho explored the world, and many knew of their name, until one day Zho returned to their Playground, only to find their temple destroyed and their followers murdered. It was at that moment Zho’s Wall was born, Zho poured their sorrow and pain into this Wall, and then disappeared.” Cecil pauses for a moment before pulling a plain case out from underneath his robes. The case has writing on it you don’t recognize and a golden leaf adorns the latch. Considering the splendor of Cecil’s home, the box seems positively ordinary in comparison. “We know this story thanks to ancient wizards of the Golden Leaf who traveled to the Playground – few survived, but this – this is the only relic we have from that time.” Cecil opens the case and before you can see what’s inside, a powerful shock wave unlike anything you’ve ever experienced hits you. The sound of the ocean, the roar of the wind, the frigidness of snow, and the scalding heat of boiling water overwhelms your senses. You fall off your chair and see Thomas sitting, staring rapturously at the box. Cecil abruptly closes the box and the sensation is immediately gone. “I should have warned you, this is an item of immense Power. I call it Zho’s Dagger, and it most certainly is the item that killed Zho.” A quietness covers the room as the enormity of Cecil’s words wash over you. “I gather now, you understand the enormity of what I am about to suggest. I want you to revisit Zho’s Playground, bring this dagger with you and use its power to counteract the Power of Zho’s Wall and go inside and understand what happened, and bring me back something.” Thomas blinks, “And fish.” Cecil smiles, “Yes, and fish.” Thomas looks at you and without hesitation blurts out, “We’ll do it! What do you want in return?” Cecil shakes his head and looks away for a moment, “A safer world for us all, and some information I’ve long pondered. Consider this journey the favor I ask of you…and maybe a few rare things I’ve misplaced. But mostly the first thing.” Cecil hands the box to Thomas. “Keep it secret, keep it safe, and when you approach the wall open the box and hold onto that dagger with all your will. Now, I have important things to be doing.” Cecil looks expectantly at you both and you get the impression it’s your time to leave. `,
    skills:[{skill:"Fishing",value:90},],
    previous:"A Wall In The Way XI",
    next:"A Wall In The Way XIII",
    requests:[{label:"Gold Potato",quantity:1,inventory:0},
    {label:"Gold Boot",quantity:2,inventory:0},
    {label:"Gold Coral",quantity:200,inventory:0},
    {label:"Gold Jelly",quantity:200,inventory:0},
    {label:"Goldray",quantity:200,inventory:0},
    {label:"Gold Flier",quantity:200,inventory:0},
    ],
    rewards:[{label:"Zho's Dagger",quantity:1,},
    ],
    current:false,},

    {questline:"A Wall In The Way",
    quest:"A Wall In The Way XIII",
    info:`You both leave Cecil’s house in a rushed fog. Thomas has the plain case close to him. “Well, that was…interesting. I’m not so worried about all the high-falutin god stuff, but think of the riches! The fame! The prestige! Lucky for you, I happen to have a backup store, in case I need to get out of town a second time in a hurry. Let’s go tomorrow! Skip town before Lorn and anyone else realize we’ve gone. They’ll only try to stop us anyways…” You cautiously agree, remembering the argument between Lorn and Star. You put your misgivings aside for your friend, and you prepare yourself for another long trek north in the morning. `,
    skills:[{skill:"Fishing",value:90},],
    previous:"A Wall In The Way XII",
    next:"A Wall In The Way XIV",
    requests:[{label:"Skipjack",quantity:600,inventory:0},
    {label:"Broccoli",quantity:600,inventory:0},
    {label:"Grape Juice",quantity:50,inventory:0},
    {label:"Canoe",quantity:200,inventory:0},
    {label:"Rice",quantity:500,inventory:0},
    ],
    rewards:[{label:"Large Chest 01",quantity:50,},
    {label:"Treasure Key",quantity:55,},
    {label:"Gold Pea Seeds",quantity:500,},
    {label:"Popcorn",quantity:50,},
    ],
    current:false,},

    {questline:"A Wall In The Way",
    quest:"A Wall In The Way XIV",
    info:`As you prepare for sleep, a knock at the door interrupts your evening routine. You quickly stash your cookies and your accounting books in the drawer and answer the door. Lorn swings the door wide open, followed by Star who immediately begins speaking to you animatedly, “Good sir, I must protest. I cannot in good conscience allow you to go forth with this journey. Whatever Cecil has told you, I’m sure it is well intentioned, but you are messing with powers you cannot possibly understand. He has sent you to your death. How very Langstaffian of him, to send others to do his bidding.” Lorn rolls his eyes towards you, “Star, why are you here, exactly? You refuse to help, you refuse to not help, and you refuse to keep to yourself. Are you not the town mage…” “Wizard.” Star mumbles absentmindedly. “...that we have trusted all these long years? Either speak plainly, or kindly stop speaking at all.” Star looks to Lorn for a moment, and you can see his internal struggle before he smooths his robes and takes a deep breath. “There are powers in this world even I do not dare trifle with, but if I cannot convince you to change your mind, I shall share with you the only helpful legend I know regarding Zho. His followers were known to be extraordinarily kind, and when in his domain you had but to ‘speak the ancient word for friend’. What happens beyond that is something only the gods know now.” Star pauses for a moment before practically pleading with you. “Consider once last time staying home and safe - ignore this fools errand.” You shake your head, intent on ensuring Thomas’ safety. Star looks quietly to Lorn and disappears in a cloud of feathers but words echo, “Friendship. More enriches life, less offers nothing.” Lorn looks quietly to you, “Whatever ails Thomas, he seems inextricably bound in all this, in ways I don’t understand and no one will explain to me, for better or worse. I…don’t want either of you to go. I’m a fool - I believed Thomas having a goal would help heal him, instead I’ve put you both in terrible, terrible danger.” Lorn pauses a moment, and a single tear runs down his left cheek. “Even now, I realize I’m not too old to have new regrets, new follies. Be safe. Bring my friend back safely.” Lorn lingers a moment longer, seemingly wanting to say more but he turns slowly and steps out of the house and you are left alone, feeling as though you’re on the precipice of something bigger than you understand. `,
    skills:[{skill:"Fishing",value:90},],
    previous:"A Wall In The Way XIII",
    next:"A Wall In The Way XV",
    requests:[{label:"Chum",quantity:600,inventory:0},
    {label:"Gold Feather",quantity:250,inventory:0},
    {label:"Gold Leaf",quantity:250,inventory:0},
    {label:"Blue Feathers",quantity:600,inventory:0},
    {label:"Herbs",quantity:500,inventory:0},
    ],
    rewards:[{label:"Wizard Hat",quantity:1,},
    ],
    current:false,},

    {questline:"A Wall In The Way",
    quest:"A Wall In The Way XV",
    info:`The morning is clear, and you wake up to finish your final chores before Thomas arrives. Thomas’ enthusiasm is apparent, he practically runs and skips as you depart. With no cart and the food in your packs, you expect to make excellent time. With no significant rain, and having recently traveled this way, you are able to pick your way back north faster than you expected. After a few days on the journey, Thomas seems quieter than usual. You reflect, for a moment before realizing he seems almost unrecognizable from the man you met when you moved to Redbrook. His drive, confidence, intensity and joy for adventure are far removed from the nervous, novice fisherman you met all that time ago. As you approach the snowy phenomenon, you find Jill’s snow machine waiting for you, looking worn and covered in a few weeks of outdoor weather, but otherwise in good working order. “What luck! This will cut down our snow travel considerably!” You press the big red start button and the machine sputters and whirs to life briefly before it dies. “Must be out of corn oil.” Thomas quips. Luckily, you brought some spare. `,
    skills:[{skill:"Fishing",value:90},],
    previous:"A Wall In The Way XIV",
    next:"The Fall of Water I",
    requests:[{label:"Corn Oil",quantity:250,inventory:0},
    ],
    rewards:[{label:"Silver",quantity:2147483647,},
    {label:"Coal",quantity:600,},
    {label:"Black Powder",quantity:600,},
    {label:"Arnold Palmer",quantity:500,},
    {label:"Gold Pepper Seeds",quantity:500,},
    ],
    current:false,},

    ////////////////////////////////////////////////////////////////////////

    {questline:"The Smell of a Fun Guy",
    quest:"The Smell of a Fun Guy I",
    info:`Mariya is looking for a new ingredient for her cooking. The town gala is coming and she wants to showcase something truly unique and wonderful for the residents of Redbrook. However, she is at a loss on what new ingredient she could find to really make her dish pop. She wants to ask Holger for his advice, but would like to have a peace offering before she consults him, would you bring some of Holger's favorite things to help smooth their introduction? `,
    skills:[{skill:"Farming",value:99},{skill:"Fishing",value:99},{skill:"Crafting",value:99},{skill:"Exploring",value:99},],
    previous:undefined,
    next:"The Smell of a Fun Guy II",
    requests:[{label:"Gold Trout",quantity:1000,inventory:0},
    {label:"Potato",quantity:1000,inventory:0},
    {label:"Mug of Beer",quantity:50,inventory:0},
    ],
    rewards:[{label:"Cabbage Stew",quantity:2,},
    {label:"Horn",quantity:250,},
    {label:"Cheese",quantity:50,},
    ],
    current:false,},

    {questline:"The Smell of a Fun Guy",
    quest:"The Smell of a Fun Guy II",
    info:`Holger was of course, delighted by the gifts Mariya brought him. He immediately suggested that you could try adding potatoes and radishes to your food to make them more interesting. Mariya seemed a bit skeptical, but she soldiered on, and of course asked you to provide her with the requisite items. `,
    skills:[{skill:"Farming",value:99},{skill:"Fishing",value:99},{skill:"Crafting",value:99},{skill:"Exploring",value:99},],
    previous:"The Smell of a Fun Guy I",
    next:"The Smell of a Fun Guy III",
    requests:[{label:"Potato",quantity:1000,inventory:0},
    {label:"Radish",quantity:1000,inventory:0},
    ],
    rewards:[{label:"Lemon Cream Pie",quantity:2,},
    ],
    current:false,},

    {questline:"The Smell of a Fun Guy",
    quest:"The Smell of a Fun Guy III",
    info:`Mariya was quite disappointed by the outcome of her radish and potato pie - it didn't at all encapsulate the richness and body that she wanted to showcase her talents with. She suggests maybe some less traditional ingredients for her dishes, and asks if you'd be interested in helping her with her new idea. `,
    skills:[{skill:"Farming",value:99},{skill:"Fishing",value:99},{skill:"Crafting",value:99},{skill:"Exploring",value:99},],
    previous:"The Smell of a Fun Guy II",
    next:"The Smell of a Fun Guy IV",
    requests:[{label:"Peas",quantity:1000,inventory:0},
    {label:"Pumpkin",quantity:1000,inventory:0},
    {label:"Puffer",quantity:1000,inventory:0},
    {label:"Rice",quantity:1000,inventory:0},
    ],
    rewards:[{label:"Shrimp-a-Plenty",quantity:3,},
    ],
    current:false,},

    {questline:"The Smell of a Fun Guy",
    quest:"The Smell of a Fun Guy IV",
    info:`"Well, peas excuse me, but that combination didn't work either..." Mariya seems a bit frustrated, but she was grateful that Charles and frank seemed to enjoy the conglomeration food idea (minus the fish). You'd like to cheer Mariya up a little bit, maybe some flowers would help her feel better? `,
    skills:[{skill:"Farming",value:99},{skill:"Fishing",value:99},{skill:"Crafting",value:99},{skill:"Exploring",value:99},],
    previous:"The Smell of a Fun Guy III",
    next:"The Smell of a Fun Guy V",
    requests:[{label:"Purple Flower",quantity:1000,inventory:0},
    {label:"Sunflower",quantity:1000,inventory:0},
    ],
    rewards:[{label:"Grab Bag 03",quantity:250,},
    ],
    current:false,},

    {questline:"The Smell of a Fun Guy",
    quest:"The Smell of a Fun Guy V",
    info:`Mariya seemed slightly cheered by your thoughtful gift, but also a little distracted as she is whipping up a new idea. She asks if you could grab her some more items while she's perfecting the ratios in her current idea. You swear she is muttering something about how "Ariathan dishes always had such richness of flavor..." `,
    skills:[{skill:"Farming",value:99},{skill:"Fishing",value:99},{skill:"Crafting",value:99},{skill:"Exploring",value:99},],
    previous:"The Smell of a Fun Guy IV",
    next:"The Smell of a Fun Guy VI",
    requests:[{label:"Flour",quantity:1000,inventory:0},
    {label:"Bacon",quantity:1000,inventory:0},
    {label:"Beet",quantity:1000,inventory:0},
    {label:"Mushroom",quantity:1000,inventory:0},
    {label:"Mushroom Stew",quantity:20,inventory:0},
    ],
    rewards:[{label:"Large Chest 02",quantity:250,},
    ],
    current:false,},

    {questline:"The Smell of a Fun Guy",
    quest:"The Smell of a Fun Guy VI",
    info:`Mariya seems positively delighted by your selection of items, but there's still something missing in her mind. It will have to be something rare you guess, and you suddenly remember frank discussing some odd behavior with your pigs the other day. You figure frank would want some really odd items so you set about finding some strange things to curry favor. `,
    skills:[{skill:"Farming",value:99},{skill:"Fishing",value:99},{skill:"Crafting",value:99},{skill:"Exploring",value:99},],
    previous:"The Smell of a Fun Guy V",
    next:"The Smell of a Fun Guy VII",
    requests:[{label:"Gold Carrot",quantity:1000,inventory:0},
    {label:"Grasshopper",quantity:1000,inventory:0},
    {label:"Caterpillar",quantity:1000,inventory:0},
    {label:"Bucket",quantity:1000,inventory:0},
    {label:"Carrot",quantity:1000,inventory:0},
    {label:"Blue Feathers",quantity:1000,inventory:0},
    {label:"Feathers",quantity:1000,inventory:0},
    {label:"Blue Dye",quantity:1000,inventory:0},
    ],
    rewards:[{label:"Apple Cider",quantity:250,},
    {label:"Orange Juice",quantity:750,},
    ],
    current:false,},

    {questline:"The Smell of a Fun Guy",
    quest:"The Smell of a Fun Guy VII",
    info:`"well, i could talk to them for you, but then that would be spoiling the surprise, wouldn't it?" frank seems nonplussed when you ask him for help on the pig situation. "but, i suppose if you gave me some delightful items for...reasons i could help you out...maybe..." `,
    skills:[{skill:"Farming",value:99},{skill:"Fishing",value:99},{skill:"Crafting",value:99},{skill:"Exploring",value:99},],
    previous:"The Smell of a Fun Guy VI",
    next:"The Smell of a Fun Guy VIII",
    requests:[{label:"Chum",quantity:1000,inventory:0},
    {label:"Carved Bear",quantity:5,inventory:0},
    {label:"Carved Camel",quantity:5,inventory:0},
    {label:"Carved Moose",quantity:5,inventory:0},
    {label:"Carved Owl",quantity:5,inventory:0},
    {label:"Carved Rabbit",quantity:5,inventory:0},
    {label:"Carved Rhino",quantity:5,inventory:0},
    {label:"Carved Warthog",quantity:5,inventory:0},
    {label:"Cannon",quantity:1000,inventory:0},
    {label:"Old Boot",quantity:1000,inventory:0},
    {label:"Amber Cane",quantity:25,inventory:0},
    {label:"Small Flute",quantity:25,inventory:0},
    ],
    rewards:[{label:"Arnold Palmer",quantity:1000,},
    {label:"Cranberry Juice",quantity:1,},
    ],
    current:false,},

    {questline:"The Smell of a Fun Guy",
    quest:"The Smell of a Fun Guy VIII",
    info:`You bring back a bunch of items frank needs for no obviously nefarious purpose, and in return he gives you a big grin and bunny wink. "yeah, i can wink, you can get over yourself now. anyways, i found this in star's basement the other day, and maybe you could take the pigs for a walk, maybe they'll find something special, if you are nice to them every day and feed them." frank hops around the assortment of items and you hear a sound that sounds like someone yelling in surprise, you turn your head to see where it came from, and when you look back, you see a small collar where frank had been. `,
    skills:[{skill:"Farming",value:99},{skill:"Fishing",value:99},{skill:"Crafting",value:99},{skill:"Exploring",value:99},],
    previous:"The Smell of a Fun Guy VII",
    next:"The Smell of a Fun Guy IX",
    requests:[{label:"Feathers",quantity:1000,inventory:0},
    {label:"Bucket",quantity:1000,inventory:0},
    {label:"Wooden Table",quantity:1000,inventory:0},
    ],
    rewards:[{label:"Pig Collar",quantity:1,},
    ],
    current:false,},

    {questline:"The Smell of a Fun Guy",
    quest:"The Smell of a Fun Guy IX",
    info:`Your pigs seem to quite enjoy the freedom of walks and the feedings, and while it looks a bit ridiculous, when you take them through the forest, sometimes they insistently stop and with some snuffling and squealing, they reveal a mushroom you're not quite familiar with. You think Mariya might be interested, so you gather a few to bring to her. `,
    skills:[{skill:"Farming",value:99},{skill:"Fishing",value:99},{skill:"Crafting",value:99},{skill:"Exploring",value:99},],
    previous:"The Smell of a Fun Guy VIII",
    next:"The Smell of a Fun Guy X",
    requests:[{label:"White Truffle",quantity:120,inventory:0},
    ],
    rewards:[{label:"Silver",quantity:21000000000,},
    ],
    current:false,},

    {questline:"The Smell of a Fun Guy",
    quest:"The Smell of a Fun Guy X",
    info:`Mariya added the white truffles to her dish and was overcome with emotion after her first tasting. After a moment she begins to share how the taste took her back to her hometown, to the Emperor’s Ball. It was on the second night after Emperor Ariathes returned to his ancestral homeland for the first time since ascending the Cascading Throne. It was an amazing time. Actually, it may have started Mariya’s journey to becoming a chef. The celebration food was all so amazing and vibrant and delicious. Mariya dreamed of creating something so spectacular. As the memory washes over her, Mariya sheds a single tear, and you extend your thanks to her for sharing a little bit about her unknown past this day. Mariya mentions she remembers a different variety of truffles now that her memory has been jogged, and would love to have some of the rarer black truffles, if you come across them. `,
    skills:[{skill:"Farming",value:99},{skill:"Fishing",value:99},{skill:"Crafting",value:99},{skill:"Exploring",value:99},{skill:"Tower",value:1},],
    previous:"The Smell of a Fun Guy IX",
    next:undefined,
    requests:[{label:"Black Truffle",quantity:58,inventory:0},
    ],
    rewards:[{label:"Silver",quantity:40000000000,},
    ],
    current:false,},

    ////////////////////////////////////////////////////////////////////////
    
]
